/****** Script do comando SelectTopNRows de SSMS  ******/

/* OPERADOR IN: FILTRO DE MULTIPLAS CONDIÇÕES
DETERMINA SE UM VALOR CORRESPONDE A QUALQUER VALOR EM UMA SUBCONSULTA OU LISTA
RETORNA SEMPRE TRUE OU FALSE. 
PODE SUSBSTITUIR O OR DE QUERIES COM MAIS DE UMA CONDIÇÃO */

/* UTILIZANDO O IN NESTA CONSULTA, ELA VAI RETORNAR TODOS OS VALORES ONDE OS TIPOS DE CAFÉ, SÃO 'COM LEITE' OU 'CAPUCCINO' */

SELECT * FROM CONSUMO2 
WHERE [TIPOS DE CAFÉ] IN ('COM LEITE','CAPUCCINO') AND CONSUMISTA IS NOT NULL

/* UTILIZANDO O NOT IN NESTA CONSULTA, RETORNAMOS OS VALORES ONDE OS TIPO DE CAFÉ NÃO SÃO 'COM LEITE' OU 'CAPUCCINO' */

SELECT * FROM CONSUMO2 
WHERE [TIPOS DE CAFÉ] NOT  IN ('COM LEITE','CAPUCCINO') AND CONSUMISTA IS NOT NULL AND CONSUMISTA = 'SIM'

/* TESTANDO COM TRÊS CONDIÇÕES */

SELECT * FROM CONSUMO2 
WHERE [TIPOS DE CAFÉ] NOT  IN ('COM LEITE','CAPUCCINO','ADOÇADO') AND CONSUMISTA IS NOT NULL AND CONSUMISTA = 'SIM'
