/* UTILIZANDO O JOIN E INNER JOIN */ 

/* AS JOINS SÃO UTILIZADAS PARA OBTER DADOS PROVENIENTES DE DUAS OU MAIS TABELAS, BASEADO EM UM RELACIONAMENTO ENTRE COLUNAS NESTAS TABELAS */

/* TEMOS DOIS TIPOS DE JOINS : INNER JOIN RETORNAR LINHAS QUANDO HOUVER PELO MENOS UMA CORRESPONDÊNCIA EM AMBAS AS TABELAS.
                               OUTER JOIN : RETORNA LINHAS MESMO QUANDO NÃO HOUVE PELO MENOS UMA CORRESPONDÊNCIA EM UMA DAS TABELAS (OU AMBAS). 
							   O OUTER JOIN DIVIDE-SE EM: LEFT JOIN, RIGHT JOIN E FULL JOIN 

							   */

/* SELECIONANDO TODAS AS COLUNAS DE AMBAS AS TABELAS */

SELECT * FROM dbo.ANALISES
INNER JOIN dbo.CONSUMO2
ON ANALISES.CONSUMISTA = CONSUMO2.CONSUMISTA

/* SELECIONANDO COLUNAS ESPECIFICAS EM AMBAS AS TABELAS */ 

SELECT ANALISES.CONSUMISTA, ANALISES.IDADE, CONSUMO2.[TIPOS DE CAFÉ]
FROM ANALISES
INNER JOIN CONSUMO2
ON ANALISES.CONSUMISTA = CONSUMO2.CONSUMISTA

/* UTILIZANDO OS ALIASES PARA OTIMIZAR O CODIGO */

SELECT A.CONSUMISTA, A.IDADE, C.[TIPOS DE CAFÉ]
FROM ANALISES AS A 
INNER JOIN CONSUMO2  AS C
ON A.CONSUMISTA = C.CONSUMISTA

/* UTILIZANDO WHERE COM O INNER JOIN */ 

SELECT A.CONSUMISTA, A.IDADE, C.[TIPOS DE CAFÉ]
FROM ANALISES AS A 
INNER JOIN CONSUMO2  AS C
ON A.CONSUMISTA = C.CONSUMISTA
WHERE A.CONSUMISTA = 'SIM'

/* LEFT JOIN: RETORNA TODAS AS LINHAS DA TABELA ESQUERDA, MESMO SE NÃO HOUVER NENHUMA CORRESPONDENCIA NA TABELA A DIREITA
   RIGHT JOIN: RETORNA TODAS AS LINHAS DA TABELA ESQUEDA, MESMO SE NÃO HOUVER NENHUMA CORRESPONDENCIA NA TABELA A DIREITA
   FULL  JOIN: RETORNA LINHAS QUANDO HOUVER UMA CORRESPONDÊNCIA EM QUALQUER UMA DAS TABELAS. É UMA COMBINAÇÃO DE LEFT E RIGHT JOINS.
*/ 



/* MUNDANDO ALGUNS DADOS PARA CONSEGUIR UTILIZAR OS EXEMPLOS DE JOIN */

SELECT COUNT(ENTREVISTADOS) AS 'ENTREVISTADOS', ESCOLARIDADE, CONSUMISTA FROM ANALISES
GROUP BY ESCOLARIDADE, CONSUMISTA

UPDATE ANALISES
SET CONSUMISTA = NULL
WHERE ESCOLARIDADE = 'Superior completo' AND CONSUMISTA = 'NÃO'

SELECT COUNT(ENTREVISTADOS) AS 'ENTREVISTADOS', ESCOLARIDADE, CONSUMISTA FROM ANALISES
GROUP BY ESCOLARIDADE, CONSUMISTA

/* UTILIZANDO O LEFT JOIN */

SELECT A.CONSUMISTA, A.IDADE,A.ESCOLARIDADE, C.[TIPOS DE CAFÉ]
FROM ANALISES AS A 
INNER JOIN CONSUMO2  AS C
ON A.CONSUMISTA = C.CONSUMISTA
WHERE A.ESCOLARIDADE = 'Superior completo'
GROUP BY A.ESCOLARIDADE, A.CONSUMISTA, A.IDADE, C.[TIPOS DE CAFÉ]

/* VERIFICAMOS QUE AO UTILIZAR O INNER JOIN, ESTÁ NOS RETORNANDO APENAS OS VALORES EM QUE AS COLUNAS POSSUEM VALORES CORRESPONDENTES
COMO NO EXEMPLO ANTERIOR, NÓS TRANSFORMAMOS TODOS OS NÃO CONSUMISTAS QUE TEM UMA ESCOLARIDADE = SUPERIOR COMPLETO EM 'NULL', ESTES NÃO 
FORAM RETORNADOS. VAMOS VERIFICAR AGORA UTILIZANDO O LEFT JOIN */

SELECT A.CONSUMISTA, A.IDADE,A.ESCOLARIDADE, C.[TIPOS DE CAFÉ]
FROM ANALISES AS A 
LEFT JOIN CONSUMO2  AS C
ON A.CONSUMISTA = C.CONSUMISTA
WHERE A.ESCOLARIDADE = 'Superior completo'
GROUP BY A.ESCOLARIDADE, A.CONSUMISTA, A.IDADE, C.[TIPOS DE CAFÉ]

/* OBSERVAMOS QUE, AO UTILIZARMOS O LEFT JOIN TEMOS TODOS OS DADOS COM ESCOLARIDADE 'SUPERIOR COMPLETO' MESMO QUANDO NÃO SÃO CORRESPONDENTE,
VAMOS TESTAR AGORA O RIGHT JOIN */ 


SELECT A.IDADE,A.ESCOLARIDADE, C.[TIPOS DE CAFÉ], C.CONSUMISTA
FROM ANALISES AS A 
LEFT JOIN CONSUMO2  AS C
ON A.CONSUMISTA = C.CONSUMISTA
WHERE A.ESCOLARIDADE = 'Superior completo'
GROUP BY A.ESCOLARIDADE, C.CONSUMISTA, A.IDADE, C.[TIPOS DE CAFÉ]


/* UTILIZANDO AGORA O RIGHT JOIN */

SELECT C.CONSUMISTA, A.ESCOLARIDADE, C.ENTREVISTADOS, C.[TIPOS DE CAFÉ]
FROM CONSUMO2 AS C 
RIGHT JOIN ANALISES AS A
ON C.CONSUMISTA = A.CONSUMISTA
WHERE A.ESCOLARIDADE = 'Superior completo'
GROUP BY C.CONSUMISTA, C.[TIPOS DE CAFÉ], A.ESCOLARIDADE, C.ENTREVISTADOS

/* FULL JOIN TRÁS TODOS OS DADOS EM AMBAS AS TABELAS */

SELECT C.CONSUMISTA, A.ESCOLARIDADE, C.ENTREVISTADOS, C.[TIPOS DE CAFÉ]
FROM CONSUMO2 AS C 
FULL JOIN ANALISES AS A
ON C.CONSUMISTA = A.CONSUMISTA
WHERE A.ESCOLARIDADE = 'Superior completo'


SELECT C.CONSUMISTA, A.ESCOLARIDADE, C.ENTREVISTADOS, C.[TIPOS DE CAFÉ]
FROM CONSUMO2 AS C 
FULL JOIN ANALISES AS A
ON C.CONSUMISTA = A.CONSUMISTA
WHERE A.ESCOLARIDADE IS NULL