/* COMANDOS LIKE E NOT LIKE */ 

SELECT * FROM dbo.ANALISES
WHERE CONSUMISTA IS NOT NULL

/* ESCOLHENDO ONDE A ESCOLARIDADE COMEÇA COM 1° */

SELECT * FROM dbo.ANALISES
WHERE CONSUMISTA IS NOT NULL AND ESCOLARIDADE LIKE '1°%'

/* PARA ESCOLHER POR EXEMPLO, SÓ O QUE TIVEREM COMPLETO NO GRAU DE ESCOLARIDADE */ 

SELECT * FROM dbo.ANALISES
WHERE CONSUMISTA IS NOT NULL AND ESCOLARIDADE LIKE '% completo'

/* ESCOLHENDO APENAS OS DADOS EM QUE O NIVEL DE ESCOLARIDADE NÃO É INCOMPLETO */ 

SELECT * FROM dbo.ANALISES
WHERE CONSUMISTA IS NOT NULL AND ESCOLARIDADE NOT LIKE '% incompleto'

