/****** Script do comando SelectTopNRows de SSMS  ******/
/**SELECT [CONSUMISTA]
      ,[ENTREVISTADOS]
      ,[SEXO]
      ,[IDADE]
      ,[EST#CIVIL]
      ,[ESCOLARIDADE]
      ,[OCUPACAO]
      ,[ATRIB# COMPRA DE CAFÉ]
      ,[ASPECTOS AO NÃO CONSUMO]
      ,[BEBIDAS QUE SUBSTITUEM O CAFÉ]
      ,[ATRIBUTOS ISOLADOS DO PRODUTO]
  FROM [consumocafe].[dbo].[ANALISE] ***/

  /* PRIMEIRA CONSULTA, VERIFICANDO QUANTOS INTREVISTADOS DISSERAM SIM E NÃO */ 
  /* O COMANDO AS 'ENTREVISTADOS' SERVE PARA RENOMEAR A COLUNA DE ENTREVISTADOS' */ 
  SELECT CONSUMISTA, 
  AS 'ENTREVISTADOS' FROM consumocafe.dbo.ANALISE  
  WHERE CONSUMISTA IS NOT NULL
  GROUP BY CONSUMISTA

  /* VERIFICANDO A IDADE MEDIA DOS CONSUMISTAS E NÃO CONSUMISTAS */ 

  SELECT CONSUMISTA, AVG(IDADE) AS 'IDADE MEDIA' FROM consumocafe.dbo.ANALISE
  WHERE CONSUMISTA IS NOT NULL
  GROUP BY CONSUMISTA

  /* VERIFICANDO O SEXO DOS CONSUMISTAS DE CAFÉ, OBSERVAMOS QUE OS ENTREVISTADOS DO SEXO MASCULINO CONSOMEM MAIS CAFÉ, PORÉM OS RESULTADOS PODEM
  ESTAR ENVIESADOS, JÁ QUE A MAIORIA DO PUBLICO ENTREVISTADO ERA DO SEXO MASCULINO */

  SELECT CONSUMISTA, SEXO, COUNT(ENTREVISTADOS) AS 'ENTREVISTADOS' FROM consumocafe.dbo.ANALISE
  WHERE CONSUMISTA IS NOT NULL AND CONSUMISTA = 'SIM'
  GROUP BY CONSUMISTA, SEXO

  /* VERIFICANDO ASPECTOS DO NÃO CONSUMO AO CAFÉ, OS PRINCIPAIS MOTIVOS DO NÃO CONSUMO SÃO ATRIBUIDOS A: NÃO GOSTAR DE CAFÉ B: FALTA DE HABITO. */
  SELECT CONSUMISTA, [ASPECTOS AO NÃO CONSUMO], COUNT(ENTREVISTADOS) AS 'ENTREVISTADOS' FROM consumocafe.dbo.ANALISE
  WHERE CONSUMISTA IS NOT NULL AND CONSUMISTA = 'NÃO'
  GROUP BY CONSUMISTA, [ASPECTOS AO NÃO CONSUMO]
  ORDER BY ENTREVISTADOS DESC 

  /* OBSERVAMOS QUE, A MAIORIA DAS PESSOAS QUE NÃO CONSOMEM CAFÉ, PREFEREM BEBIDAS COMO: LEITE E SUCOS. */ 

  SELECT CONSUMISTA,[BEBIDAS QUE SUBSTITUEM O CAFÉ], COUNT(ENTREVISTADOS) AS 'ENTREVISTADOS' FROM consumocafe.dbo.ANALISE
  WHERE CONSUMISTA IS NOT NULL AND CONSUMISTA = 'NÃO'
  GROUP BY CONSUMISTA, [BEBIDAS QUE SUBSTITUEM O CAFÉ]
  ORDER BY ENTREVISTADOS DESC 
